name: "Deploy Full Stack"

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'preview'
        type: choice
        options:
          - preview
          - production
      tag_name:
        description: 'Tag name (e.g. v0.1.0). If empty, uses v__VERSION__'
        required: false
        type: string
        default: ''

jobs:
  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets: inherit

  deploy-desktop:
    uses: ./.github/workflows/deploy-desktop.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      tag_name: ${{ github.event.inputs.tag_name }}
    secrets: inherit
